import 'package:example/demo/waoui/progress/_index.dart' as progress;
import 'package:example/demo/waoui/datePicker/_index.dart' as date_picker;
import 'package:example/demo/waoui/tag/_index.dart' as tag;
import 'package:example/demo/waoui/skeleton/_index.dart' as skeleton;
import 'package:example/demo/waoui/result/_index.dart' as result;
import 'package:example/demo/waoui/cascader/_index.dart' as cascader;
import 'package:example/demo/waoui/tree/_index.dart' as tree;
import 'package:example/demo/waoui/form/_index.dart' as form;
import 'package:example/demo/waoui/inputNumber/_index.dart' as input_number;
import 'package:example/demo/waoui/select/_index.dart' as select;
import 'package:example/demo/waoui/dateTimePicker/_index.dart'
    as date_time_picker;
import 'package:example/demo/waoui/upload/_index.dart' as upload;
import 'package:example/demo/waoui/radio/_index.dart' as radio;
import 'package:example/demo/waoui/pageHeader/_index.dart' as page_header;
import 'package:example/demo/waoui/slider/_index.dart' as slider;
import 'package:example/demo/waoui/tabs/_index.dart' as tabs;
import 'package:example/demo/waoui/input/_index.dart' as input;
import 'package:example/demo/waoui/timePicker/_index.dart' as time_picker;
import 'package:example/demo/waoui/checkbox/_index.dart' as checkbox;
import 'package:example/demo/waoui/message/_index.dart' as message;
import 'package:example/demo/waoui/timeline/_index.dart' as timeline;
import 'package:example/demo/waoui/dialog/_index.dart' as dialog;
import 'package:example/demo/waoui/notification/_index.dart' as notification;
import 'package:example/demo/waoui/rate/_index.dart' as rate;
import 'package:example/demo/waoui/popover/_index.dart' as popover;
import 'package:example/demo/waoui/divider/_index.dart' as divider;
import 'package:example/demo/waoui/transfer/_index.dart' as transfer;
import 'package:example/demo/waoui/colorPicker/_index.dart' as color_picker;
import 'package:example/demo/waoui/card/_index.dart' as card;
import 'package:example/demo/waoui/calendar/_index.dart' as calendar;
import 'package:example/demo/waoui/swatch/_index.dart' as swatch;
import 'package:example/demo/waoui/collapse/_index.dart' as collapse;
import 'package:example/demo/waoui/backtop/_index.dart' as backtop;
import 'package:example/demo/waoui/infiniteScroll/_index.dart'
    as infinite_scroll;
import 'package:example/demo/waoui/messageBox/_index.dart' as message_box;
import 'package:example/demo/waoui/breadcrumb/_index.dart' as breadcrumb;
import 'package:example/demo/waoui/steps/_index.dart' as steps;
import 'package:example/demo/waoui/dropdown/_index.dart' as dropdown;
import 'package:example/demo/waoui/menu/_index.dart' as menu;
import 'package:example/demo/waoui/popconfirm/_index.dart' as popconfirm;
import 'package:example/demo/waoui/alert/_index.dart' as alert;
import 'package:example/demo/waoui/tooltip/_index.dart' as tooltip;
import 'package:example/demo/waoui/carousel/_index.dart' as carousel;
import 'package:example/demo/waoui/image/_index.dart' as image;
import 'package:example/demo/waoui/loading/_index.dart' as loading;
import 'package:example/demo/waoui/button/_index.dart' as button;
import 'package:example/demo/waoui/container/_index.dart' as container;
import 'package:example/demo/waoui/drawer/_index.dart' as drawer;
import 'package:example/demo/waoui/avatar/_index.dart' as avatar;
import 'package:example/demo/waoui/badge/_index.dart' as badge;
import 'package:example/demo/waoui/descriptions/_index.dart' as descriptions;
import 'package:example/demo/waoui/pagination/_index.dart' as pagination;
import 'package:example/demo/waoui/empty/_index.dart' as empty;
import 'package:example/demo/waoui/table/_index.dart' as table;

registWaoUI() {
  button.regist();
  container.regist();
  drawer.regist();
  avatar.regist();
  badge.regist();
  descriptions.regist();
  pagination.regist();
  empty.regist();

  progress.regist();
  date_picker.regist();
  tag.regist();
  skeleton.regist();
  result.regist();
  cascader.regist();
  tree.regist();
  input_number.regist();
  select.regist();
  date_time_picker.regist();
  upload.regist();
  radio.regist();
  page_header.regist();
  slider.regist();
  tabs.regist();
  form.regist();
  input.regist();
  time_picker.regist();
  checkbox.regist();
  message.regist();

  timeline.regist();
  dialog.regist();
  notification.regist();
  popover.regist();
  transfer.regist();
  color_picker.regist();
  card.regist();
  calendar.regist();
  swatch.regist();
  collapse.regist();
  backtop.regist();
  infinite_scroll.regist();
  message_box.regist();
  breadcrumb.regist();
  steps.regist();
  dropdown.regist();
  menu.regist();
  popconfirm.regist();
  alert.regist();
  tooltip.regist();
  carousel.regist();
  image.regist();
  loading.regist();
  rate.regist();
  divider.regist();
  table.regist();
}
