name: example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-172.0.dev <3.0.0"
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  wao_ui: 
    path:  ../


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  bitsdojo_window: 
    git:
      url: https://github.com/CorvusYe/bitsdojo_window
      path: bitsdojo_window

  # flutter_md: 
  #   path: ../../flutter_md
  flutter_markdown: 
    git:
      url: https://github.com/CorvusYe/flutter_markdown
  url_launcher: ^6.1.0
    # path: D:/work/codes/gitee/flutter_markdown

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # image
    - assets/image/htw.jpg
    - assets/image/wth.jpg
    - logo.png
    - assets/dart_syntax.json
    # doc
    - assets/md/waoui/about/conscience.md
    - assets/md/waoui/about/plan.md
    - assets/md/waoui/about/thinking.md
    - assets/md/waoui/basic/WButton.md
    - assets/md/waoui/basic/WContainer.md
    - assets/md/waoui/data/WAvatar.md
    - assets/md/waoui/data/WBadge.md
    - assets/md/waoui/data/WDescriptions.md
    - assets/md/waoui/data/WEmpty.md
    - assets/md/waoui/data/WPagination.md
    - assets/md/waoui/data/WProgress.md
    - assets/md/waoui/data/WResult.md
    - assets/md/waoui/data/WTable.md
    - assets/md/waoui/data/WSkeleton.md
    - assets/md/waoui/data/WTag.md
    - assets/md/waoui/data/WTree.md
    - assets/md/waoui/form/WForm.md
    - assets/md/waoui/form/WCheckbox.md
    - assets/md/waoui/form/WCascader.md
    - assets/md/waoui/form/WDatePicker.md
    - assets/md/waoui/form/WColorPicker.md
    - assets/md/waoui/form/WDateTimePicker.md
    - assets/md/waoui/form/WRadio.md
    - assets/md/waoui/form/WSlider.md
    - assets/md/waoui/navigation/WBreadcrumb.md
    - assets/md/waoui/form/WInputNumber.md
    - assets/md/waoui/form/WInput.md
    - assets/md/waoui/notice/WLoading.md
    - assets/md/waoui/notice/WMessageBox.md
    - assets/md/waoui/navigation/WDropdown.md
    - assets/md/waoui/form/WSelect.md
    - assets/md/waoui/notice/WNotification.md
    - assets/md/waoui/navigation/WTabs.md
    - assets/md/waoui/others/WCalendar.md
    - assets/md/waoui/notice/WAlert.md
    - assets/md/waoui/others/WCard.md
    - assets/md/waoui/navigation/WMenu.md
    - assets/md/waoui/others/WDivider.md
    - assets/md/waoui/form/WSwitch.md
    - assets/md/waoui/form/WTimePicker.md
    - assets/md/waoui/form/WUpload.md
    - assets/md/waoui/others/WCarousel.md
    - assets/md/waoui/notice/WMessage.md
    - assets/md/waoui/others/WTimeline.md
    - assets/md/waoui/others/WTooltip.md
    - assets/md/waoui/others/WDialog.md
    - assets/md/waoui/others/WCollapse.md
    - assets/md/waoui/form/WTransfer.md
    - assets/md/waoui/others/WImage.md
    - assets/md/waoui/others/WBacktop.md
    - assets/md/waoui/others/WInfiniteScroll.md
    - assets/md/waoui/others/WPopconfirm.md
    - assets/md/waoui/others/WPopover.md
    - assets/md/waoui/form/WRate.md
    - assets/md/waoui/navigation/WSteps.md
    - assets/md/waoui/others/WDrawer.md
    - assets/md/waoui/navigation/WPageHeader.md
    # Material md
    - assets/md/material/basic/Button.md
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: PingFang
      fonts:
        - asset: packages/wao_ui/fonts/PingFang.ttf
          weight: 600